# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "84ea256426b476e9df7b2e91db506da8"
name = "manage-product-post"
handle = "manage-product-post"
# Sử dụng domain trycloudflare.com cho app (không thể dùng domain của store)
application_url = "https://investor-revealed-prototype-concerts.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://hamilton-noted-cubic-estimated.trycloudflare.com/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://hamilton-noted-cubic-estimated.trycloudflare.com/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_content,write_content,read_files,write_files"

[auth]
# Sử dụng domain trycloudflare.com cho authentication
redirect_urls = ["https://investor-revealed-prototype-concerts.trycloudflare.com/auth/callback", "https://investor-revealed-prototype-concerts.trycloudflare.com/auth/shopify/callback", "https://investor-revealed-prototype-concerts.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
